# Generated by Django 4.0.1 on 2022-04-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_cirricullar', models.CharField(blank=True, max_length=25, null=True)),
                ('extra_curricullar', models.CharField(blank=True, max_length=25, null=True)),
                ('sports', models.CharField(blank=True, max_length=25, null=True)),
                ('other', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'achievements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(db_column='AGE')),
                ('credential', models.CharField(blank=True, max_length=45, null=True)),
                ('coll_location', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'college',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, db_column='Fname', max_length=45, null=True)),
                ('fage', models.CharField(blank=True, db_column='Fage', max_length=45, null=True)),
                ('faddress', models.CharField(blank=True, db_column='Faddress', max_length=45, null=True)),
                ('fnumber', models.CharField(blank=True, db_column='Fnumber', max_length=45, null=True)),
                ('fmail', models.CharField(blank=True, db_column='Fmail', max_length=45, null=True)),
                ('fqualify', models.CharField(blank=True, db_column='Fqualify', max_length=45, null=True)),
                ('foccupation', models.CharField(blank=True, db_column='Foccupation', max_length=45, null=True)),
            ],
            options={
                'db_table': 'father',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.CharField(max_length=45)),
                ('value2', models.CharField(blank=True, max_length=45, null=True)),
                ('value3', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Internals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_no', models.IntegerField(db_column='SEM_No')),
                ('sub_1', models.CharField(blank=True, db_column='SUB_1', max_length=25, null=True)),
                ('sub_2', models.CharField(blank=True, db_column='SUB_2', max_length=25, null=True)),
                ('sub_3', models.CharField(blank=True, db_column='SUB_3', max_length=25, null=True)),
                ('sub_4', models.CharField(blank=True, db_column='SUB_4', max_length=25, null=True)),
                ('sub_5', models.CharField(blank=True, db_column='SUB_5', max_length=25, null=True)),
                ('sub_6', models.CharField(blank=True, db_column='SUB_6', max_length=25, null=True)),
            ],
            options={
                'db_table': 'internals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('password', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(blank=True, db_column='Mname', max_length=54, null=True)),
                ('mage', models.CharField(blank=True, db_column='Mage', max_length=45, null=True)),
                ('maddress', models.CharField(blank=True, db_column='Maddress', max_length=45, null=True)),
                ('mnumber', models.CharField(blank=True, db_column='Mnumber', max_length=45, null=True)),
                ('mmail', models.CharField(blank=True, db_column='Mmail', max_length=45, null=True)),
                ('mqualify', models.CharField(blank=True, db_column='Mqualify', max_length=45, null=True)),
                ('moccupation', models.CharField(blank=True, db_column='Moccupation', max_length=45, null=True)),
            ],
            options={
                'db_table': 'mother',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personal1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.CharField(blank=True, max_length=25, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=45, null=True)),
                ('mothertongue', models.CharField(blank=True, max_length=45, null=True)),
                ('caste', models.CharField(blank=True, max_length=45, null=True)),
                ('guardian', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('pnumber', models.CharField(blank=True, db_column='Pnumber', max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('blood', models.CharField(blank=True, max_length=45, null=True)),
                ('disability', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'personal1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('surname', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'reg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regproc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('surname', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'regproc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem1', models.IntegerField()),
                ('sem2', models.IntegerField(blank=True, null=True)),
                ('sem3', models.IntegerField(blank=True, null=True)),
                ('sem4', models.IntegerField(blank=True, null=True)),
                ('sem5', models.IntegerField(blank=True, null=True)),
                ('sem6', models.IntegerField(blank=True, null=True)),
                ('sem7', models.IntegerField(blank=True, null=True)),
                ('sem8', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roll',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sem1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(blank=True, max_length=25, null=True)),
                ('sub2', models.CharField(blank=True, max_length=25, null=True)),
                ('sub3', models.CharField(blank=True, max_length=25, null=True)),
                ('sub4', models.CharField(blank=True, max_length=25, null=True)),
                ('sub5', models.CharField(blank=True, max_length=25, null=True)),
                ('sub6', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'sem1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sem2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(blank=True, max_length=45, null=True)),
                ('sub2', models.CharField(blank=True, max_length=45, null=True)),
                ('sub3', models.CharField(blank=True, max_length=45, null=True)),
                ('sub4', models.CharField(blank=True, max_length=45, null=True)),
                ('sub5', models.CharField(blank=True, max_length=45, null=True)),
                ('sub6', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sem2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sem3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(blank=True, max_length=45, null=True)),
                ('sub2', models.CharField(blank=True, max_length=45, null=True)),
                ('sub3', models.CharField(blank=True, max_length=45, null=True)),
                ('sub4', models.CharField(blank=True, max_length=45, null=True)),
                ('sub5', models.CharField(blank=True, max_length=45, null=True)),
                ('sub6', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sem3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sem4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(blank=True, max_length=45, null=True)),
                ('sub2', models.CharField(blank=True, max_length=45, null=True)),
                ('sub3', models.CharField(blank=True, max_length=45, null=True)),
                ('sub4', models.CharField(blank=True, max_length=45, null=True)),
                ('sub5', models.CharField(blank=True, max_length=45, null=True)),
                ('sub6', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sem4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sem5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(blank=True, max_length=45, null=True)),
                ('sub2', models.CharField(blank=True, max_length=45, null=True)),
                ('sub3', models.CharField(blank=True, max_length=45, null=True)),
                ('sub4', models.CharField(blank=True, max_length=45, null=True)),
                ('sub5', models.CharField(blank=True, max_length=45, null=True)),
                ('sub6', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sem5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sem6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(blank=True, max_length=45, null=True)),
                ('sub2', models.CharField(blank=True, max_length=45, null=True)),
                ('sub3', models.CharField(blank=True, max_length=45, null=True)),
                ('sub4', models.CharField(blank=True, max_length=45, null=True)),
                ('sub5', models.CharField(blank=True, max_length=45, null=True)),
                ('sub6', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sem6',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sem7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(blank=True, max_length=45, null=True)),
                ('sub2', models.CharField(blank=True, max_length=45, null=True)),
                ('sub3', models.CharField(blank=True, max_length=45, null=True)),
                ('sub4', models.CharField(blank=True, max_length=45, null=True)),
                ('sub5', models.CharField(blank=True, max_length=45, null=True)),
                ('sub6', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sem7',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sem8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(blank=True, max_length=45, null=True)),
                ('sub2', models.CharField(blank=True, max_length=45, null=True)),
                ('sub3', models.CharField(blank=True, max_length=45, null=True)),
                ('sub4', models.CharField(blank=True, max_length=45, null=True)),
                ('sub5', models.CharField(blank=True, max_length=45, null=True)),
                ('sub6', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sem8',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sibling1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1name', models.CharField(blank=True, db_column='S1name', max_length=45, null=True)),
                ('s1gender', models.CharField(blank=True, db_column='S1gender', max_length=25, null=True)),
                ('s1age', models.CharField(blank=True, db_column='S1age', max_length=45, null=True)),
                ('s1address', models.CharField(blank=True, db_column='S1address', max_length=45, null=True)),
                ('s1number', models.CharField(blank=True, db_column='S1number', max_length=45, null=True)),
                ('s1mail', models.CharField(blank=True, db_column='S1mail', max_length=45, null=True)),
                ('s1qualify', models.CharField(blank=True, db_column='S1qualify', max_length=45, null=True)),
                ('s1occupation', models.CharField(blank=True, db_column='S1occupation', max_length=45, null=True)),
            ],
            options={
                'db_table': 'sibling1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sibling2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s2name', models.CharField(blank=True, db_column='S2name', max_length=45, null=True)),
                ('s2gender', models.CharField(blank=True, db_column='S2gender', max_length=25, null=True)),
                ('s2address', models.CharField(blank=True, db_column='S2address', max_length=45, null=True)),
                ('s2age', models.CharField(blank=True, db_column='S2age', max_length=45, null=True)),
                ('s2number', models.CharField(blank=True, db_column='S2number', max_length=45, null=True)),
                ('s2mail', models.CharField(blank=True, db_column='S2mail', max_length=45, null=True)),
                ('s2qualify', models.CharField(blank=True, db_column='S2qualify', max_length=45, null=True)),
                ('s2occupation', models.CharField(blank=True, db_column='S2occupation', max_length=45, null=True)),
            ],
            options={
                'db_table': 'sibling2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sibling3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3name', models.CharField(blank=True, db_column='S3name', max_length=45, null=True)),
                ('s3gender', models.CharField(blank=True, db_column='S3gender', max_length=45, null=True)),
                ('s3age', models.CharField(blank=True, db_column='S3age', max_length=45, null=True)),
                ('s3address', models.CharField(blank=True, db_column='S3address', max_length=50, null=True)),
                ('s3number', models.CharField(blank=True, db_column='S3number', max_length=45, null=True)),
                ('s3mail', models.CharField(blank=True, db_column='S3mail', max_length=45, null=True)),
                ('s3qualify', models.CharField(blank=True, db_column='S3qualify', max_length=45, null=True)),
                ('s3occupation', models.CharField(blank=True, db_column='S3occupation', max_length=45, null=True)),
            ],
            options={
                'db_table': 'sibling3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('proof', models.CharField(db_column='PROOF', max_length=50)),
                ('age', models.IntegerField(db_column='AGE')),
                ('address', models.CharField(db_column='ADDRESS', max_length=50)),
            ],
            options={
                'db_table': 'stud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='studcred',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mothertongue', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adminsite_studcred',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('proof', models.CharField(db_column='PROOF', max_length=50)),
                ('age', models.IntegerField(db_column='AGE')),
                ('address', models.CharField(db_column='ADDRESS', max_length=50)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.CharField(max_length=45)),
                ('value2', models.CharField(blank=True, max_length=45, null=True)),
                ('value3', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'table2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usere',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('proof', models.CharField(db_column='PROOF', max_length=50)),
                ('age', models.IntegerField(db_column='AGE')),
                ('address', models.CharField(db_column='ADDRESS', max_length=50)),
            ],
            options={
                'db_table': 'usere',
                'managed': False,
            },
        ),
    ]
