# Generated by Django 3.2.12 on 2022-12-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0002_auto_20221212_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='disease',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
